name: DevSecOps CI/CD Pipeline for OWASP Juice Shop

on:
  push:
    branches:
      - master

permissions:
  contents: write
  security-events: write

jobs:
  # Step 1: Build Juice Shop
  build:
    name: Build and Deploy Juice Shop
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Juice Shop Docker Image
        run: docker pull bkimminich/juice-shop

  # Step 2: Security Testing
  security_testing:
    name: Security Testing
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      # SAST: CodeQL Security Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"
          output: "codeql-results"

      # SCA: Snyk Vulnerability Scanning
      - name: Run Snyk Scan
        uses: snyk/actions/node@v2
        with:
          command: test --json > snyk-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # DAST: OWASP ZAP Dynamic Analysis
      - name: Start Juice Shop Container
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
          sleep 30

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j -J zap-results.json --verbose'

      # Upload Scan Results
      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            codeql-results
            snyk-results.json
            zap-results.json

      # - name: Install Snyk CLI
      #   run: npm install -g snyk
      # - name: Run Snyk for Dependency Scanning
      #   run: snyk test --all-projects

      # - name: Set up OWASP ZAP
      #   uses: zaproxy/action-full-scan@v0.7.0
      #   env:
      #     ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
      # - name: Run OWASP ZAP DAST scan
      #   run: |
      #     docker run --rm -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-stable zap-full-scan.py -t http://localhost:3000

  # vulnerability_management:
  #   name: Manage & Visualize Vulnerabilities
  #   runs-on: ubuntu-latest
  #   needs: security_testing

  #   steps:
  #     - name: Install SonarQube Scanner
  #       run: |
  #         curl -sSLo sonarqube-scanner-cli.zip https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip
  #         unzip sonarqube-scanner-cli.zip -d $HOME
  #         export PATH=$HOME/sonar-scanner-*/bin:$PATH

  #     - name: Run SonarQube scan
  #       run: |
  #         sonar-scanner \
  #           -Dsonar.projectKey=juice-shop \
  #           -Dsonar.sources=. \
  #           -Dsonar.host.url=https://sonarcloud.io \
  #           -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

  redeploy:
    name: Redeploy Juice Shop
    runs-on: ubuntu-latest
    needs: security_testing

    steps:
      - name: Pull Latest Juice Shop Docker Image
        run: docker pull bkimminich/juice-shop

      - name: Redeploy Juice Shop
        run: |
          docker stop juice-shop || true
          docker rm juice-shop || true
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop